[workspace]
resolver = "2"
members = [
    "crates/saft",
    "crates/saft-bytecode", "crates/saft-cli",
    "crates/saft-ir",
    "crates/saft-macro",
    "crates/saft-syntax",
    "tests",
]
default-members = ["crates/saft-cli"]

[workspace.dependencies]
codespan-reporting = "0.11.1"
