[package]
name = "saft"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = { workspace = true }
saft-bytecode = { path = "../saft-bytecode" }
saft-ir = { path = "../saft-ir" }
saft-syntax = { path = "../saft-syntax" }
