name: Test

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly

          cargo build

          cargo test --all

  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly
          rustup component add rustfmt

          cargo fmt --all --check

  lint:
    name: Lint

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -DWarnings

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly
          rustup component add clippy

          cargo clippy --all-targets --all-features
